[package]
name = "emtk_launcher"
version.workspace = true
authors.workspace = true
edition.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
clap = { version = "4.5", features = ["derive"] }
detours-sys.workspace = true
emtk_core = { path = "../emtk_core" }
emtk_framework = { path = "../emtk_framework" }
getset = "0.1"
iced = { git = "https://github.com/iced-rs/iced", branch = "master", features = [
	"advanced",
	"highlighter",
	"lazy",
	"markdown",
	"svg",
	"tokio",
] }
iced_drop = { git = "https://github.com/ProffDea/iced_drop.git", branch = "dev" }
iced_split = { git = "https://github.com/edwloef/iced_split.git", branch = "main" }
iced_table = { git = "https://github.com/reirao/EXAMINER.git", branch = "iced-table" }
image.workspace = true
open.workspace = true
rfd = "0.15"
ron.workspace = true
serde.workspace = true
termimad = "0.31"
thiserror.workspace = true
tokio.workspace = true
toml.workspace = true
tracing.workspace = true
tracing-appender.workspace = true
tracing-subscriber.workspace = true
tracing-tracy.workspace = true

[build-dependencies]
winresource = "0.1"

[dev-dependencies]
tempfile.workspace = true
