[package]
name = "examiner"
version = "0.2.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/reirao/EXAMINER"
description = "Independent native Windows hooks for Exanima"

[lib]
name = "examiner_runtime"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "examiner"
path = "src/main.rs"

[[bin]]
name = "examiner_test_host"
path = "src/test_host.rs"

[dependencies]

[profile.release]
strip = "debuginfo"

